apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_demo_1.name }}
spec:
  type: {{ .Values.service.app_demo_1.type }}
  ports:
    - port: {{ .Values.service.app_demo_1.port }}
      targetPort: {{ .Values.service.app_demo_1.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.app_demo_1.name }}
